### ISSUE TITLE
Binary file for Windows has to be executable .exe

### ISSUE THREAD

**Issue by ayankelevich-ugcs** [ugcs/dronelogbook#16]
Now it is hard to run application. It requires knowledge how to run .jar files

**Comment by Gendalfion** [comment]
@ayankelevich-ugcs you can check out windows executable distribution on [release page](https://github.com/ugcs/dronelogbook/releases) or you can download the latest available build from the following [link](https://ugcs.github.io/dronelogbook/ucsHub.exe).
