### ISSUE TITLE
Marks for uploaded flights

### ISSUE THREAD

**Issue by Gendalfion** [ugcs/dronelogbook#27]
Flights which has been uploaded to LogBook should be marked in the flight list.

**Comment by kkbrass** [comment]
Upload indicator is not saved after restarting the app. The upload indicator should persist through restart. 

Also, if I try to upload a flight that has already been uploaded and the app realizes it's a duplicate, no uploaded indicator is displayed. I think that once it realizes the flight has been uploaded, the indicator should be added.

**Comment by Gendalfion** [comment]
"The upload indicator should persist through restart." - extracted that feature in the separate issue #73
