### ISSUE TITLE
Fix notification window icons

### ISSUE THREAD

**Issue by kkbrass** [ugcs/dronelogbook#52]
After flight upload a confirmation window is shown. This window has a Java icon. This icon needs to be changed to a green checkmark. Same way - when there is a problem uploading, a black exclamation mark in a yellow triangle can be shown, similar to as it is now, just without Java icon.

**Comment by Gendalfion** [comment]
The issue seems to be reproduced only for mac system. 
Tried it in Windows 10 - there is no icon displayed for the report window at all.
@kkbrass it would be helpful if you supply a screenshot for the report window in mac.

**Comment by kkbrass** [comment]
<img width="450" alt="screenshot 2018-11-20 at 15 38 39" src="https://user-images.githubusercontent.com/11043861/48777224-b6e09f80-ecda-11e8-838c-e9a4706389bf.png">
<img width="753" alt="screenshot 2018-11-20 at 11 45 12" src="https://user-images.githubusercontent.com/11043861/48777225-b6e09f80-ecda-11e8-91ad-78d74d3604d0.png">
<img width="750" alt="screenshot 2018-11-20 at 11 47 08" src="https://user-images.githubusercontent.com/11043861/48777226-b7793600-ecda-11e8-9870-2a3367e2f57d.png">
<img width="748" alt="screenshot 2018-11-20 at 15 37 05" src="https://user-images.githubusercontent.com/11043861/48777227-b7793600-ecda-11e8-9928-c88c96ef585d.png">
