### ISSUE TITLE
Fix Drone ID not shown on DroneLogBook after uploading

### ISSUE THREAD

**Issue by kkbrass** [ugcs/dronelogbook#53]

**Comment by Gendalfion** [comment]
I tried to upload a flight with arbitrary DroneId with importFlight [service](https://www.dronelogbook.com/webservices/importFlight-ugcs.html) and can't figure where is this id is actually displayed on DroneLogBook site.
The uploader tool now uploads drone name and drone serial number as "droneId" parameter. With my tests, drone name is correctly uploaded to DroneLogBook and displayed within the flight (if there is a drone with the same name registered in the pilot profile)

**Comment by kkbrass** [comment]
Upload matches ok when a drone profile exists on the site with the same serial number. When there is no such drone the flight still uploads as well. From what I gather it's an issue on DroneLogbook side? Closing issue.
