### ISSUE TITLE
Change icons to new Telemetry Sync Tool icons

### ISSUE THREAD

**Issue by kkbrass** [ugcs/dronelogbook#70]
Currently icons still have the text Upload Tool. Since the name of the app has changed, icon name also needs to go with it. Created new icons with text "T-Sync Tool".

Please find icon files and the PNG attached to the issue.

![icon](https://user-images.githubusercontent.com/11043861/50909186-01a5aa80-1434-11e9-9500-25108358aab3.png)

[TelemetrySyncTool Icons.zip](https://github.com/ugcs/dronelogbook/files/2741469/TelemetrySyncTool.Icons.zip)

**Comment by Gendalfion** [comment]
@kkbrass, seems that icon for mac is damaged somehow in the tar.gz. 
It's possible to reassemble the archive?

**Comment by kkbrass** [comment]
Mac icon looks good, but Windows icon does not, can't read the text. Need to investigate.

**Comment by Gendalfion** [comment]
> Mac icon looks good, but Windows icon does not, can't read the text. Need to investigate.

I think the problem caused by Windows scaling algorithm - it's not working well for high-resolution icons. We need to provide pre-rendered icons with different resolutions into the *.ico file.
